### ISSUE TITLE
Campos decimais('invalid class typecast')

### ISSUE THREAD

**Issue by faelmoroni** [ezequieljuliano/DataSetJSONConverter4Delphi#14]
Bom dia!
Primeiramente parabéns pelo framework, muito útil. Estou começando a utilizar este framework e me deparei com a seguinte situação:
em numa tabela(Firebird 2.5) eu tenho um campo definido como decimal(5,2). Ao gerar um ClientDataSet para esta tabela eu estou definindo o campo como Float. No momento em que eu executo o seguinte comando 'RESTRequest.Execute' é mostrado a seguinte mensagem de erro: 'invalid class typecast'. Se este campo for alterado para decimal(10,2) ou maior não ocorre o erro.
Tentei fazer algumas alterações mas não obtive sucesso.
O framework está atualizado(29/05/2018).
Tem alguma ideia do que pode ser?
Att.,
Rafael Moroni

**Comment by ezequieljuliano** [comment]
Bom dia.

Você teria como anexar seu exemplo para que eu possa verificar o que pode estar ocorrendo?

**Comment by ezequieljuliano** [comment]
Fechada devido a inatividade.
