### ISSUE TITLE
JSONToStructure com TFDMemTable problema a criação dos FIELDs

### ISSUE THREAD

**Issue by eduardomrj** [ezequieljuliano/DataSetJSONConverter4Delphi#15]
Essa classe foi criada para aceitar apenas TClientDataset ?

Ao tentar testar utilizando a classe TFDMemTable eu não posso abrir a tabela sem antes definir os FIELDs.

Tive que remover as linhas onde verifica se a tabela já está aberta

**Comment by ezequieljuliano** [comment]
Ela deve aceitar qualquer descendente de TDataSet. Eu fiz uma alteração no teste unitário para utilizar o TFDMemTable e o funcionamento foi normal:

![image](https://user-images.githubusercontent.com/1966730/44031587-d7707228-9eda-11e8-85c8-058a077850ea.png)
