### ISSUE TITLE
ftByte is not handled

### ISSUE THREAD

**Issue by ertankucukoglu** [ezequieljuliano/DataSetJSONConverter4Delphi#18]
Hello,

I have an SQL Server table with tinyint column. That column translates as ftByte.

ftByte raises an exception "Cannot find type for field..."

I have added ftByte among ftInteger group. Writing in here just to let you know about issue.

Thanks.

--Ertan

**Comment by ezequieljuliano** [comment]
Okay. There are these differences between the different drivers.

Would you like to make a pull request for this change?

**Comment by ezequieljuliano** [comment]
Task with no return.
