### ISSUE TITLE
Forma de criar os campos do dataset

### ISSUE THREAD

**Issue by fabricio-sisplan** [ezequieljuliano/DataSetJSONConverter4Delphi#26]
Existe alguma forma de criar os campos do dataset direto de um jsonArray ou jsonObject?
Tentei procurar pelo ToStructure mas parece que não existe mais.

**Comment by ezequieljuliano** [comment]
Provavelmente ocorreu um problema ao fazer um merge com um pull request, pois este método deveria estar disponível. Vou verificar os commits e reverter o que causou a remoção.

**Comment by ezequieljuliano** [comment]
Reverti o pull request que causou o problema.
