### ISSUE TITLE
Field do tipo UUID

### ISSUE THREAD

**Issue by andeerc** [ezequieljuliano/DataSetJSONConverter4Delphi#28]
Estou usando UUID como pk nas tabelas, com banco postgres, ai na hora de converter o dataset para json ocorre uma exceção dizendo que não encontrou um tipo correto para esse campo. Obs, não estou criando os fields na query, apenas fazendo o open no sql. Existe alguma solução que não seja criar todos os campos no dataset?

**Comment by attikov** [comment]
in DataSetToJSONObject() -> case Dataset.Fields[i].DataType of add

case Dataset.Fields[i].DataType of
// if Delphi version > where ftGuid was introduced
          TFieldType.ftGuid:
              Result.AddPair(key, Dataset.Fields[i].AsString);
// endif

**Comment by ezequieljuliano** [comment]
Could you do a PR with this improvement?

**Comment by andeerc** [comment]
Sim, irei implementar e envio o PR.

**Comment by ezequieljuliano** [comment]
@AndersondaCampo faz um tempo já, mas conseguiu trabalhar no PR para este ponto?

**Comment by andeerc** [comment]
@ezequieljuliano feito!
