### ISSUE TITLE
TDataSetConverter.DataSetToJSONArray

### ISSUE THREAD

**Issue by NelsonLima07** [ezequieljuliano/DataSetJSONConverter4Delphi#5]
Acredito que essa função deve ter um "DataSet.DisableControls" antes de iniciar o loop e consequentemente um "DataSet.EnableControls" ao final do processo. Ou colocar como opção.

**Comment by ezequieljuliano** [comment]
Sim, eu já tinha pensado a respeito disso. Hoje eu deixo isso a cargo de quem for usar a biblioteca, pois existem situações onde não se pode desabilitar os controles. Desta forma, antes de iniciar a conversão você desabilita e depois de efetuar ela você habilita. Mas vou pensar em uma maneira de deixar isso configurável.
