### ISSUE TITLE
Problemas Conversao de Data no SQLSERVER

### ISSUE THREAD

**Issue by medreis** [ezequieljuliano/DataSetJSONConverter4Delphi#7]
Ezequiel
Existe um problema na conversão do DataSet.AsJSONArray,  para campos datetime no SQLSERVER 

Este campos no firedac são do tipo TSQLTimeStampField   e na conversao do da rotina DataSetConvert4D.imp , estes campos ficam sem a parte da DATA, acredito que o tipo deva estar na opção de TFieldType.ftDateTime também.

   **TFieldType.ftTimeStamp,** TFieldType.ftTime:
          begin
            if not dataSet.Fields[i].IsNull then
            begin
              timeStamp := dataSet.Fields[i].AsSQLTimeStamp;
              Result.AddPair(key, TJSONString.Create(SQLTimeStampToStr('hh:nn:ss', timeStamp)));
            end
            else
              Result.AddPair(key, TJSONNull.Create);

**Comment by ezequieljuliano** [comment]
Realizei a troca da conversão do ftTimeStamp para respeitar a mesma regra do ftDateTime.
