### ISSUE TITLE
Omitir Campos

### ISSUE THREAD

**Issue by fcmatos** [ezequieljuliano/DataSetJSONConverter4Delphi#8]
Na conversão de DataSet para Json existe alguma maneira de omitir alguns campos?
Ao gerar json para enviar para inclusão ou alteração as vezes não queremos incluir campos de data/hora ou o campo de id no caso de novo cadastro.

Desde já obrigado.

**Comment by hunsche** [comment]
Boa tarde,
Já foi realizado a implementação se quiser acompanhar o pull request segue o [link](https://github.com/ezequieljuliano/DataSetConverter4Delphi/pull/17).

**Comment by ezequieljuliano** [comment]
Obrigado @hunsche

**Comment by viniciussanchez** [comment]
@hunsche @ezequieljuliano eu vi aqui a implementação... mas estava pensando em algo ainda mais performático... Porque temos que retornar um JSON com campos null? Exemplo:

`{
    "ID": 9,
    "DESCRICAO": "SCRIPT INCLUIDO",
    "CONTEUDO_SCRIPT": "insert into script",
    "OCORRENCIA": 123456,
    "ID_BANCO": 44,
    "REINDEXA": "S",
    "DEMORADO": "S",
    "BACKUP": "N",
    "USUARIO_CONECTADO": "N",
    "ID_CLIENTE": 46,
    "DATA_INC": "2019-05-03T10:06:09.653Z",
    "LOGIN_INC": "JWT",
    "DATA_ALT": null,
    "LOGIN_ALT": null,
    "NUMERO": 585
}`

Não tem necessidade de aparecer esse DATA_ALT E LOGIN_ALT... eu já ajustei aqui os fontes para isso... mas não sei se vocês tem uma regra melhor, e também não sei se isso se aplicaria para todos os casos...
